name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  node_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Create NYC folder
      run: mkdir .nyc_output
    - name: Install Dependencies
      run: npm install
    - name: Run tests
      run: npm run enforce
    - name: Coverage
      run: npm run test-lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}